# name:                pe200012-github-io
# version:             0.1.0.0
# dependencies:
# - base >= 4.7 && < 5
# - regex-base
# - regex-tdfa
# - hakyll

# executables:
#   site:
#     main: site.hs
#     source-dirs: ./
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - pe200012-github-io

name:                pe200012-github-io
version:             0.1.0.0

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Arbitrage#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll
- regex-tdfa
- process
- bytestring
- shelly
- directory
- extra

executables:
  site:
    main:                site.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
